// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {MASPVerifier} from "../src/MASPVerifier.sol";
import {BLS12381} from "../src/BLS12381.sol";
import {Groth16Verifier} from "../src/Groth16Verifier.sol";

/// @title Real Groth16 Proof Verification Tests
/// @notice Tests verification of actual Groth16 proofs generated by the Rust prover
/// @dev These proofs are for a multiplication circuit: x * y = z
///      Generated using bellman with BLS12-381 curve
contract RealProofVerificationTest is Test {
    MASPVerifier public verifier;

    // ============ Verification Key from Rust Prover ============
    // Circuit: x * y = z (multiplication)
    // Generated with bellman on BLS12-381

    bytes constant VK_ALPHA = hex"0000000000000000000000000000000011510e82cee26d26da160f681fbdd253cd766dfe6350af5ef160f16b936a1635c6657f9042c0d026ed4946c0dd015ada000000000000000000000000000000001352adb9cd63363068985568e84d82ded28446647d941affb07fe087bdff22bbebbb3355db2555eb020ef12d6f2886f8";

    bytes constant VK_BETA = hex"000000000000000000000000000000001094fce9c874f094e7082d1b9d5ab0f2632f51839b1a43cf3f5570f3b741845b69ab838783e839a0d0e56f8e5da632040000000000000000000000000000000017436f49ce9170e2072926ab4259ede8ed571006c98ecf9df104e7c6b85defd7d6218af4da86a1d0c9131847e26319f90000000000000000000000000000000002e0b827418ba0426e367a7018f149b0a3a734cf18fd7c067e4c1115a419d844fe59130117a2cc7117e0a48b53bbd25b000000000000000000000000000000001038b99190781c3be5711b3fdbcbe1f37f9391b1b74b6bbeb65d1c2a81e37800891c6564bbb6df3386c1aa64515df22b";

    bytes constant VK_GAMMA = hex"000000000000000000000000000000000d70d4f82692f41e1f312b64f20a9c5c66c9bb7893d8ad511ca0178917d6bbdcb908c4ad7df0468b0efea5b6e74aee3300000000000000000000000000000000120cc16955a628080cff226d57b0a69e746693003c9585b7efbd01f0bcf1111a58036106ac0c31674e03b647f3bc16c50000000000000000000000000000000017b42ff611fbfbb3a7e966baa16c423421cc30933b7450c3afa9a568951b88945be628730e63a7a2280df5f8548fd4e60000000000000000000000000000000012f3265e447c0c8d0c391a71f23b115c9f0d9333eee8eb34851e7ac8a71b481ab21497a510da3d1d1ae329593f10a9d8";

    bytes constant VK_DELTA = hex"00000000000000000000000000000000108cc9d458f60730c868f8675cfcfec5fcd3a1f42b436d1f0a4d84b320edaeb4d94f45ee1ce2e8fdc961552b4c93eb7f000000000000000000000000000000000d9df374303a8e1cd940c276697117530d1ba54eddae9de17f7dd2b2250858e975f6ba4135ea7bdf68eddea2c9a21f0700000000000000000000000000000000176e1d649d65a436888df686a51cc3edb8d0fdd1955b69eb32b6ad0d4ddefdebf4e6b4196030bf04b41c5bad26bd46dc000000000000000000000000000000000978945a58f03b2900b74834e2c71cf6a6d4626147bf96613df2135326420bff2fe6b2bf72f00b163cd204c41b75fc38";

    // IC points (IC[0], IC[1] for 1 public input)
    bytes constant VK_IC_0 = hex"0000000000000000000000000000000006044ddc3a2b6dd3298a69daa53d182324a1c54a4df19ef8c25c13a7f7044f31d3b12756415d872ad608a130e5867e6e000000000000000000000000000000000da0acf7bf8abaa65eef89701359ec4c6ef5596ecab0afda0dd2de81b76e88537d046c1588d6c5a28e6eb47d73e47717";

    bytes constant VK_IC_1 = hex"0000000000000000000000000000000003b1f6f3da602b23e2d3cd37e257255f4a903245dc83c55182d3e5a7011c3b7e761e4b778ce56439be77512c756d2bcf000000000000000000000000000000000077e228573a8caa92844abfa19ab9a377045c1552ce258e573d2a3755840006dd0977e0a65f1390c4f97f16d5e2671b";

    // ============ Valid Proofs ============

    // Proof 1: 3 * 7 = 21 (0x15)
    bytes constant PROOF_1 = hex"0000000000000000000000000000000017ee64e6f70c08e6ca5ddc6306c8e36a32660cb721715a69cb552d1739ce8c9d1686d1e5a14e5730d863fb609536981a00000000000000000000000000000000180f52f01e1c7394d5959271d630f09dbf1ac1403dfe48868ac11bf6bb92fbc719efae96e9c8bc57c8615ac074e684d10000000000000000000000000000000008b69f20e3281ed66c2fea1af41e6a450095b95d8d9afb1fa6584185d0a9d30b3508c071fe3d23cbf77b6a245cb0b0170000000000000000000000000000000009240b168a7d2405584102505d70ea581866c600120cd94cf8e3ceb02c55194bedc8ae9f0dcaa095c0c580d34624b06d00000000000000000000000000000000017494ce25d330076bc7d7fceea942610a236b5d5ea23d273d48734886452c5c9260ca67b1a9b21af73b0abb6df8ab6000000000000000000000000000000000044d0bdb1fc5c342168b12d571045986dfca178353a5df129fba3167c7e6b7dd9124e4c2c981e021f1d680482df919a90000000000000000000000000000000011c97c081c4035f35c461061ce0f2a0941e2fdffb14124f106b32958ead606a11382bccd6bb1c0419191a94a3eaad00f000000000000000000000000000000001066588d2e8668119a4336baeadd9e6c74f0a66fab3dc3c1e6987a0acbcdf114f2528063ae3ce243ddf981bb7852cafb";
    bytes32 constant PUBLIC_INPUT_1 = bytes32(uint256(21)); // 3 * 7 = 21

    // Proof 2: 2 * 5 = 10 (0x0a)
    bytes constant PROOF_2 = hex"000000000000000000000000000000000a5065306c5c469f72dd7810cda730737ed9f1a437bbd4360a57b11b5a7e8f28e78313583b2dad2a235644c75e6b134c000000000000000000000000000000000283a3c1451e7ea68eda9a0eca39d302e4d621d0f5a7ae5e6fc20d2d84ce6de027a76dc70d23a8751af8fc2a1628f60500000000000000000000000000000000082c3482f1f241ed88149e8af9c165d98bc3d5b053a9fffe81a7d02b074a37c8835aeac2819846f7961bce700b4083c400000000000000000000000000000000055b2f062756234acf0b12a8530d9f2ad0d73dd779c230e519d75f40be8dde8e298c65115c7a8ebea7cf35b7e5283f1f0000000000000000000000000000000008ef7b7f3c513270a7856f0229c0e34f987e305c24f52a4f7a707ef3dd3bfd95a79f8f024a269b2e46bb10157d8cf5770000000000000000000000000000000002e096bab754aac31c7467c138e39893b689dcf068ce193cb7be353922580503fd48bbd1d6c40603c87ef3f81c84dd82000000000000000000000000000000000322d64b8741e5e34345454df04c74a340b0f229389344fc5abce367b2b7dfb7fb63ba474a3ef4f2e28ccc424b8ce4cb000000000000000000000000000000000a5b03b9e37e315b4c4932c8232ab49c4a62e551ed78f8dd48166abafc0f4af6bfabd47421b10d8f05339719826b38e1";
    bytes32 constant PUBLIC_INPUT_2 = bytes32(uint256(10)); // 2 * 5 = 10

    // Proof 3: 4 * 6 = 24 (0x18)
    bytes constant PROOF_3 = hex"000000000000000000000000000000000d52d81a3a853024c6c3eda7ef308d7fcc5d2fbed482cf123d95cc0794ac1355d151b405432e47ee55f95ebc3ad71be8000000000000000000000000000000001259645595553429e70f621f5ad0b322491bd47e50fa90f80dc94bc106ed10ee336ca53c5242f6c460b07d5b67f404ef0000000000000000000000000000000007fd2f340da25a547640813cf68db5e06b5949a6429aaf90017c00a768469f99ce21fb3034698ff4e89050bfcec051a20000000000000000000000000000000004f80b5cdbab7b3a56a11659601ece2a6767758a9b43ff2ca8b0cb71de4fa02346c6b77ff7b74b331b76bc46a22d39f30000000000000000000000000000000004d086b22a8cd322725c05825e56b1ed1d8679165bd8b29725afa411e98a2c0a19a09a0778ff733859a69cfff8139c82000000000000000000000000000000000bf40ba574b3614e95d05e9e710c731ac831ef4ba4053d47cecdf36d63e49d5f31ea62bb93dea41243c3cd0953e9a9b6000000000000000000000000000000000f32c82449bb832cd3cabf37f60386ff426ccf91faf80c4256a30abfba009023f4ddc2fe3f192fa6294bb4bb0881e4bf000000000000000000000000000000000df7121d49ba58709eab796ca9458da3e7da3bc81be37a4a0e456c09afdf88a1a47f07f98e17cbfa7dfa7df2fc1c678e";
    bytes32 constant PUBLIC_INPUT_3 = bytes32(uint256(24)); // 4 * 6 = 24

    // Proof 4: 10 * 10 = 100 (0x64)
    bytes constant PROOF_4 = hex"000000000000000000000000000000000f8b2b470f98ee8c5bbed3f20d824fe5221cf2c017cabeb44d9faf1143a7059b329583ee71e3959f49634efd478508890000000000000000000000000000000009241ea87af41591b96d36738b3e35a32c01a01e6a2473a373fde7c03613b2efb76cf979e3029af5c9b2c286b7040a0400000000000000000000000000000000146775552d451fe5957c174eb2a1707005143f90d926bbcd4e1eadcfd9a6bd0e15be28e51d4d1d5a490c3dea1ca093870000000000000000000000000000000004c6669012ca113d9eae4039baa56b277114f3637b929a3877c749c6b4d65c759eac38fb7bc22117c924cdab56e6efee000000000000000000000000000000000014186cf9139f236d2c3fe159554850b52ce4d6376b206f790f94419c5e0d9bf201e173ba8ecc9d0ac6edbd397f84b3000000000000000000000000000000000c2c5638eaaa945c98da05851f01632223a281b994da628f0d3f2c90b6fcde69dc125a707b41be56656dae4e47166f5a000000000000000000000000000000000262cefc20f92e7b1daaedc501fd741c333dc73357e31b57f65fa315c65f55506a36db5298a5fc52b36aeb595106658500000000000000000000000000000000142aba238328afae2bbd337da2b024d7f1597c3e699d05ab55d27ec67ff38b103a9e7b6471c6c455875fa94ee0bf87d0";
    bytes32 constant PUBLIC_INPUT_4 = bytes32(uint256(100)); // 10 * 10 = 100

    // Proof 5: 1 * 1 = 1 (0x01)
    bytes constant PROOF_5 = hex"00000000000000000000000000000000125d3cf4179a70e9c7015780465d505ac5560060a230319b87ce05473b098fd0df1bb4c7dfb01d3570d620e99315253c0000000000000000000000000000000009159725cd9aab7bde7e3db0099a653d6a9b3d52bf3b08c72d0d5daa506bcf8b1588d4bf053b93d21340a3118de5b78d0000000000000000000000000000000011b95fa5dd702160c859cb07da8b5008e75eda6664df6cdd889ae8328d817bc73bdc33dd2efa58deda9d7be1d15328c60000000000000000000000000000000008833aae228f311aaca624e0ca370a8ad03ccd06a78e2494919897ead82a85bb8f3eac6d3731dbb083b65187b538af650000000000000000000000000000000000e8906b87b16dd2060963274801d49b1592463e44d6f424f7b5893037c04717eff7cd03ebfcaa0fef80a4972e2037ea0000000000000000000000000000000013beff75119b19b22fb178611162c209373801fd8118ce6dfb46bebb2999069b55ba33f476a9f6df0f64670736de846100000000000000000000000000000000015eeedfd4cd4570d074c49e55413c176313dfb6930407b92788a863220ceaa54795dbc77b0e80156f7666c178e8630c0000000000000000000000000000000017ea7b37d6e1ed2cf9dff51a9c3fd48d747f5ce5403351260aeded7ff55877e7ac3afcd57fceb4438e5d680eab8e3617";
    bytes32 constant PUBLIC_INPUT_5 = bytes32(uint256(1)); // 1 * 1 = 1

    // ============ Invalid Proof ============
    // This proof was generated for 3 * 7 = 21, but we claim z = 22
    bytes constant INVALID_PROOF = hex"00000000000000000000000000000000141061f44a99040f2583e4fab20cebde434918fb1e4c76c5160e0b972d492e798e15909f212fe579ef1e77e32374729d00000000000000000000000000000000019f952ecc719bb742602a89a9aab1f44ed1b1fa26e96179fedcd7477d5b57dac52c618e8c0be15c65b8dae00346b20c00000000000000000000000000000000171a5f3433b3bf08122c17d94d77defbeed53544b259067836fc5730f6bd0635f57be1dc5e3dc7adcfd8b169c2071f5100000000000000000000000000000000130dc5a5566f887c859647c27c8059dab4e0a5db136debbe1833ac7fb9eb1ba7859a7ca4d0d789e845cf4221ebb119b9000000000000000000000000000000000ed44c8ead8847afff5792ccf20f648dd7521f8a5a280cbcb2c4159be3d739e0a73856ea97c7439591c2f8a6d8bf75e7000000000000000000000000000000001190b189a2836f63af520f229bb78045073f577cf83b7a6a9fad3e8ee4cac92df30267e31ef3358f3b958dc4556e45b50000000000000000000000000000000004ad760c124a003a0b28b19549882069a39eeb18a0dd683eb3f95df8dcdeb2e775b11d74772bbc5c5a2b8e948a942423000000000000000000000000000000000d9d2ac0a49d31bc5e7e691ba71f2801ac42fb04618872ce7e9c00dec3ef81e638d98a67a1ba59302340764d58b0a1d7";
    bytes32 constant INVALID_PUBLIC_INPUT = bytes32(uint256(22)); // Wrong! Should be 21

    function setUp() public {
        verifier = new MASPVerifier();
        _setupVerificationKey();
    }

    /// @notice Set up the verification key for the multiplication circuit
    function _setupVerificationKey() internal {
        bytes[] memory ic = new bytes[](2);
        ic[0] = VK_IC_0;
        ic[1] = VK_IC_1;

        verifier.setVerificationKey(
            MASPVerifier.CircuitType.Spend, // Using Spend circuit type for testing
            VK_ALPHA,
            VK_BETA,
            VK_GAMMA,
            VK_DELTA,
            ic
        );
    }

    // ============ Valid Proof Tests ============

    /// @notice Test verification of proof 1: 3 * 7 = 21
    function test_RealProof_3x7_21() public view {
        bytes32[] memory publicInputs = new bytes32[](1);
        publicInputs[0] = PUBLIC_INPUT_1;

        bool valid = verifier.verifyProof(
            MASPVerifier.CircuitType.Spend,
            PROOF_1,
            publicInputs
        );

        assertTrue(valid, "Proof for 3 * 7 = 21 should verify");
    }

    /// @notice Test verification of proof 2: 2 * 5 = 10
    function test_RealProof_2x5_10() public view {
        bytes32[] memory publicInputs = new bytes32[](1);
        publicInputs[0] = PUBLIC_INPUT_2;

        bool valid = verifier.verifyProof(
            MASPVerifier.CircuitType.Spend,
            PROOF_2,
            publicInputs
        );

        assertTrue(valid, "Proof for 2 * 5 = 10 should verify");
    }

    /// @notice Test verification of proof 3: 4 * 6 = 24
    function test_RealProof_4x6_24() public view {
        bytes32[] memory publicInputs = new bytes32[](1);
        publicInputs[0] = PUBLIC_INPUT_3;

        bool valid = verifier.verifyProof(
            MASPVerifier.CircuitType.Spend,
            PROOF_3,
            publicInputs
        );

        assertTrue(valid, "Proof for 4 * 6 = 24 should verify");
    }

    /// @notice Test verification of proof 4: 10 * 10 = 100
    function test_RealProof_10x10_100() public view {
        bytes32[] memory publicInputs = new bytes32[](1);
        publicInputs[0] = PUBLIC_INPUT_4;

        bool valid = verifier.verifyProof(
            MASPVerifier.CircuitType.Spend,
            PROOF_4,
            publicInputs
        );

        assertTrue(valid, "Proof for 10 * 10 = 100 should verify");
    }

    /// @notice Test verification of proof 5: 1 * 1 = 1
    function test_RealProof_1x1_1() public view {
        bytes32[] memory publicInputs = new bytes32[](1);
        publicInputs[0] = PUBLIC_INPUT_5;

        bool valid = verifier.verifyProof(
            MASPVerifier.CircuitType.Spend,
            PROOF_5,
            publicInputs
        );

        assertTrue(valid, "Proof for 1 * 1 = 1 should verify");
    }

    // ============ Invalid Proof Tests ============

    /// @notice Test that invalid proof (wrong public input) fails verification
    function test_InvalidProof_WrongPublicInput() public view {
        bytes32[] memory publicInputs = new bytes32[](1);
        publicInputs[0] = INVALID_PUBLIC_INPUT; // 22 instead of 21

        bool valid = verifier.verifyProof(
            MASPVerifier.CircuitType.Spend,
            INVALID_PROOF,
            publicInputs
        );

        assertFalse(valid, "Proof with wrong public input should fail verification");
    }

    /// @notice Test that valid proof with wrong public input fails
    function test_ValidProof_WrongPublicInput() public view {
        bytes32[] memory publicInputs = new bytes32[](1);
        publicInputs[0] = bytes32(uint256(20)); // Wrong value (should be 21)

        bool valid = verifier.verifyProof(
            MASPVerifier.CircuitType.Spend,
            PROOF_1,
            publicInputs
        );

        assertFalse(valid, "Proof with mismatched public input should fail");
    }

    // ============ Batch Verification Tests ============

    /// @notice Test batch verification of all 5 valid proofs
    function test_BatchVerify_AllValidProofs() public view {
        MASPVerifier.CircuitType[] memory types = new MASPVerifier.CircuitType[](5);
        bytes[] memory proofs = new bytes[](5);
        bytes32[][] memory publicInputs = new bytes32[][](5);

        for (uint256 i = 0; i < 5; i++) {
            types[i] = MASPVerifier.CircuitType.Spend;
            publicInputs[i] = new bytes32[](1);
        }

        proofs[0] = PROOF_1;
        publicInputs[0][0] = PUBLIC_INPUT_1;
        proofs[1] = PROOF_2;
        publicInputs[1][0] = PUBLIC_INPUT_2;
        proofs[2] = PROOF_3;
        publicInputs[2][0] = PUBLIC_INPUT_3;
        proofs[3] = PROOF_4;
        publicInputs[3][0] = PUBLIC_INPUT_4;
        proofs[4] = PROOF_5;
        publicInputs[4][0] = PUBLIC_INPUT_5;

        bool valid = verifier.batchVerifyProofs(types, proofs, publicInputs);
        assertTrue(valid, "Batch verification of all valid proofs should pass");
    }

    /// @notice Test batch verification fails with one invalid proof
    function test_BatchVerify_OneInvalidProof() public view {
        MASPVerifier.CircuitType[] memory types = new MASPVerifier.CircuitType[](3);
        bytes[] memory proofs = new bytes[](3);
        bytes32[][] memory publicInputs = new bytes32[][](3);

        for (uint256 i = 0; i < 3; i++) {
            types[i] = MASPVerifier.CircuitType.Spend;
            publicInputs[i] = new bytes32[](1);
        }

        proofs[0] = PROOF_1;
        publicInputs[0][0] = PUBLIC_INPUT_1;
        proofs[1] = INVALID_PROOF;
        publicInputs[1][0] = INVALID_PUBLIC_INPUT; // Invalid
        proofs[2] = PROOF_3;
        publicInputs[2][0] = PUBLIC_INPUT_3;

        bool valid = verifier.batchVerifyProofs(types, proofs, publicInputs);
        assertFalse(valid, "Batch verification with invalid proof should fail");
    }

    // ============ Gas Benchmarks ============

    /// @notice Measure gas for single proof verification
    function test_GasBenchmark_SingleProof() public {
        bytes32[] memory publicInputs = new bytes32[](1);
        publicInputs[0] = PUBLIC_INPUT_1;

        uint256 gasBefore = gasleft();
        verifier.verifyProof(MASPVerifier.CircuitType.Spend, PROOF_1, publicInputs);
        uint256 gasUsed = gasBefore - gasleft();

        emit log_named_uint("Gas used for single real proof verification", gasUsed);
    }

    /// @notice Measure gas for batch proof verification
    function test_GasBenchmark_BatchProofs() public {
        MASPVerifier.CircuitType[] memory types = new MASPVerifier.CircuitType[](5);
        bytes[] memory proofs = new bytes[](5);
        bytes32[][] memory publicInputs = new bytes32[][](5);

        for (uint256 i = 0; i < 5; i++) {
            types[i] = MASPVerifier.CircuitType.Spend;
            publicInputs[i] = new bytes32[](1);
        }

        proofs[0] = PROOF_1;
        publicInputs[0][0] = PUBLIC_INPUT_1;
        proofs[1] = PROOF_2;
        publicInputs[1][0] = PUBLIC_INPUT_2;
        proofs[2] = PROOF_3;
        publicInputs[2][0] = PUBLIC_INPUT_3;
        proofs[3] = PROOF_4;
        publicInputs[3][0] = PUBLIC_INPUT_4;
        proofs[4] = PROOF_5;
        publicInputs[4][0] = PUBLIC_INPUT_5;

        uint256 gasBefore = gasleft();
        verifier.batchVerifyProofs(types, proofs, publicInputs);
        uint256 gasUsed = gasBefore - gasleft();

        emit log_named_uint("Gas used for batch of 5 real proof verifications", gasUsed);
    }
}
